enable-module-update = true
remove-rv-integrations-checks = true
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/xChickens/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
build-mode = "module"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"

[Music]
build-mode = "module"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"

[GooglePhotos]
build-mode = "module"
patches-source = "RookieEnough/De-Vanced"
rv-brand = "DeVanced"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.photos"

[Sync]
build-mode = "module"
patches-source = "wchill/patcheddit"
rv-brand = "patcheddit"
archive-dlurl = "https://archive.org/download/xChickens-apks/apks/com.laurencedawson.reddit_sync"
patcher-args = "-e 'Spoof client' -Oclient-id=yH0aTnJEt6qUgGn835B4vg"
version = "v23.06.30-13:39"

[Prime-Video] 
build-mode = "module"
arch = "arm64-v8a"
patches-source = "hoo-dles/morphe-patches"
archive-dlurl = "https://archive.org/download/xChickens-apks/apks/com.amazon.avod.thirdpartyclient"

[Facebook]
build-mode = "module"
arch = "arm64-v8a"
patches-source = "RookieEnough/De-Vanced"
rv-brand = "DeVanced"
archive-dlurl = "https://archive.org/download/xChickens-apks/apks/com.facebook.katana"

[Strava]
build-mode = "module"
arch = "arm64-v8a"
patches-source = "RookieEnough/De-Vanced"
rv-brand = "DeVanced"
archive-dlurl = "https://archive.org/download/xChickens-apks/apks/com.strava"

[Twitch]
build-mode = "module"
arch = "arm64-v8a"
patches-source = "RookieEnough/De-Vanced"
rv-brand = "DeVanced"
archive-dlurl = "https://archive.org/download/xChickens-apks/apks/tv.twitch.android.app"
