enable-module-update = true # set this to false if you do not want to receive updates for the module
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/xChickens/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube-Morphe]
app-name = "YouTube"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube"
uptodown-dlurl = "https://youtube.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.youtube"
build-mode = "module"

[Music-Morphe]
app-name = "Music"
patches-source = "MorpheApp/morphe-patches"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
arch = "arm64-v8a"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music"
uptodown-dlurl = "https://youtube-music.en.uptodown.com/android"
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
build-mode = "module"

[Sync-Morphe]
app-name = "Sync"
patches-source = "wchill/patcheddit"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
archive-dlurl = "https://archive.org/download/xChickens-apks/apks/com.laurencedawson.reddit_sync"
build-mode = "module"
patcher-args = "-e 'Spoof client' -Oclient-id=FnRpt2V-yImkvii9BZM_3Q"
version = "v23.06.30-13:39"

[Twitter-Morphe]
app-name = "Twitter"
patches-source = "crimera/piko"
cli-source = "MorpheApp/morphe-cli"
rv-brand = "Morphe"
archive-dlurl = "https://archive.org/download/xChickens-apks/apks/com.twitter.android"
build-mode = "module"
excluded-patches = "'Disunify xchat system'"
