enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Tiktok]
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
build-mode = "module"
version = "30.8.3"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
build-mode = "module"
included-patches = "'Custom branding' 'Remove player controls background'"
excluded-patches = "'Alternative thumbnails' 'Premium heading' 'Wide searchbar' 'Hide captions button' 'Hide cast button' 'Hide player buttons' 'Hide autoplay button' 'Hide video action buttons' 'Hide timestamp' 'Hide layout components' 'Hide endscreen cards' 'Hide email address' 'Disable fullscreen ambient mode' 'Disable suggested video end screen' 'Hide seekbar' 'Hide Shorts components' 'Hide info cards' 'Comments' 'Enable tablet layout' 'Tablet mini player' 'Spoof device dimensions' 'Always autorepeat' 'Announcements' 'Enable debugging' 'Disable precise seeking gesture'"

[Sync]
apkmirror-dlurl = "https://apkmirror.com/apk/red-apps-ltd/sync-for-reddit/"
build-mode = "module"

[Music]
archive-dlurl = "https://archive.org/download/jhc-apks/apks/com.google.android.apps.youtube.music"
arch = "arm64-v8a"
build-mode = "module"

[Strava]
apkmirror-dlurl = "https://www.apkmirror.com/apk/strava-inc/strava-running-and-cycling-gps/"
build-mode = "module"

